blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/ehsanul-karim-pappu/fet-lab/discussions
    about: For anything that is not a bug or a feature request.
